// A lookup table for slug-to-URL redirections
export const redirectTable: Record<string, string> = {
  animespotlight: 'https://forms.gle/38ACSWeu41pBFZqW8',
  mangaspotlight: 'https://forms.gle/mH9uv5naDSRXGZU29',
  shop: 'https://rzp.io/rzp/BengaluruAnimeClub',
  food: 'https://chat.whatsapp.com/IctnGQfw4OkFlawMl0qmBS',
  collaborationguidelines: '/contact-us/collaboration-guidelines',
  'collaboration-guidelines': '/contact-us/collaboration-guidelines',
  whatsapp: 'https://chat.whatsapp.com/LK11ZuLjXJN0v6zRvew71W',
  wa: 'https://chat.whatsapp.com/LK11ZuLjXJN0v6zRvew71W',
  'whatsapp-channel': 'https://whatsapp.com/channel/0029Va4WaK1I1rcnkEFOnV35',
  'whatsapp-clubhouse': 'https://chat.whatsapp.com/LsAeB6NjzNA995fiYk5DRd',
  x: 'https://x.com/bengaluwu',
  twitter: 'https://x.com/bengaluwu',
  instagram: 'https://instagram.com/bengaluruanimeclub/',
  ig: 'https://instagram.com/bengaluruanimeclub/',
  youtube: 'https://www.youtube.com/@BengaluruAnimeClub',
  yt: 'https://www.youtube.com/@BengaluruAnimeClub',
  discord: 'https://discord.gg/EumfnhyZvB',
  bluesky: 'https://bsky.app/profile/bac.moe',
  bsky: 'https://bsky.app/profile/bac.moe',
  facebook: 'https://www.facebook.com/bangaloreanimeclub',
  'facebook-group': 'https://facebook.com/groups/BangaloreAnimeClub/',
};
